### ISSUE TITLE
Create categorize() testing file

### ISSUE THREAD

**Issue by cgostic** [UBC-MDS/pylaundry#32]
Need tests for:
- [x] Output type
- [x] Standard accuracy (expected output)
- [x] Using `max_cat` argument
- [x] Edge cases (e.g. empty dataframes)
- [x] Invalid user inputs (test that Assert statements are in play)

**Comment by cgostic** [comment]
@zanderhinton @amank90 @arunmarria Does anyone know if we're meant to create a testing class? I currently have just a sequence of functions, but I noticed in examples from previous years that a class was built to test each function that itself contains testing functions.

**Comment by zanderhinton** [comment]
@cgostic Which repo's are you looking at? The ones I glanced seemed to having just a bunch of test functions listed out.

**Comment by cgostic** [comment]
@zanderhinton some of the 2018 ones...maybe too far back 😬

**Comment by cgostic** [comment]
Tests written and all pass. 100% line coverage achieved.
