### ISSUE TITLE
Feedback of Milestone 2

### ISSUE THREAD

**Issue by Doooooris** [UBC-MDS/pylaundry#60]
- Please raise error if the input is the data frame without column name for all functions. When I try df = pandas.DataFrame({[1,'x']}); categorize(df); It outputs {'numeric': [], 'categorical': [0]}. 

- test_select_features.py is not documented. For each test function, describe what does it for.

**Comment by amank90** [comment]
Addressed the second issue in #79

**Comment by cgostic** [comment]
@amank90 @arunmarria @zanderhinton we can use the assert 

`assert not isinstance(df.columns, pd.RangeIndex)`

To address this

**Comment by zanderhinton** [comment]
Addressed in all functions.
